spring:
  datasource:
    url: jdbc:mysql://120.46.159.231:3306/2022212864
    username: 2022212864
    password: 2022212864
  sql:
    init:
      mode: always

logging:
  level:
    com:
      nightlos: debug
    sql: debug
  pattern:
    console: '%-5level %C.%M[%line] - %msg%n'